"""add paper-scoped scientific records

Revision ID: 0020_paper_science_records
Revises: 0019_paper_centric_foundation
Create Date: 2026-09-16 11:16:26.172558
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0020_paper_science_records'
down_revision: Union[str, Sequence[str], None] = '0019_paper_centric_foundation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compounds',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('compound_label', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by_kind', sa.Enum('reviewer', 'admin', 'ai', 'system', name='science_creator_kind', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(compound_label) <> ''", name='ck_compounds_label_required'),
    sa.CheckConstraint("created_by_kind IN ('reviewer', 'admin', 'ai', 'system')", name='ck_compounds_creator_kind'),
    sa.CheckConstraint('sort_order >= 0', name='ck_compounds_nonnegative_order'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'paper_id'], ['paper_workspaces.id', 'paper_workspaces.paper_id'], name='fk_compounds_workspace_paper', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'paper_id', 'workspace_id', name='uq_compounds_id_paper_workspace'),
    sa.UniqueConstraint('workspace_id', 'compound_label', name='uq_compounds_workspace_label')
    )
    op.create_index('ix_compounds_workspace_order', 'compounds', ['workspace_id', 'sort_order', 'id'], unique=False)
    op.create_table('evidence',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('text', 'table', 'scheme', 'image', name='evidence_kind', native_enum=False, length=16), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('x0', sa.Numeric(precision=12, scale=10), nullable=True),
    sa.Column('y0', sa.Numeric(precision=12, scale=10), nullable=True),
    sa.Column('x1', sa.Numeric(precision=12, scale=10), nullable=True),
    sa.Column('y1', sa.Numeric(precision=12, scale=10), nullable=True),
    sa.Column('quoted_text', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('crop_asset_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('text', 'table', 'scheme', 'image')", name='ck_evidence_kind'),
    sa.CheckConstraint("source_sha256 ~ '^[0-9a-f]{64}$'", name='ck_evidence_source_sha256'),
        sa.CheckConstraint('((x0 IS NULL AND y0 IS NULL AND x1 IS NULL AND y1 IS NULL) OR (x0 IS NOT NULL AND y0 IS NOT NULL AND x1 IS NOT NULL AND y1 IS NOT NULL AND x0 >= 0 AND x0 < x1 AND x1 <= 1 AND y0 >= 0 AND y0 < y1 AND y1 <= 1))', name='ck_evidence_normalized_bbox'),
    sa.CheckConstraint('page_number > 0', name='ck_evidence_positive_page'),
    sa.ForeignKeyConstraint(['crop_asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'paper_id'], ['paper_workspaces.id', 'paper_workspaces.paper_id'], name='fk_evidence_workspace_paper', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'paper_id', 'workspace_id', name='uq_evidence_id_paper_workspace')
    )
    op.create_index('ix_evidence_workspace_page', 'evidence', ['workspace_id', 'page_number'], unique=False)
    op.create_table('lineages',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('lineage_label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(lineage_label) <> ''", name='ck_lineages_label_required'),
    sa.CheckConstraint('sort_order >= 0', name='ck_lineages_nonnegative_order'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'paper_id'], ['paper_workspaces.id', 'paper_workspaces.paper_id'], name='fk_lineages_workspace_paper', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'paper_id', 'workspace_id', name='uq_lineages_id_paper_workspace')
    )
    op.create_index('ix_lineages_workspace_order', 'lineages', ['workspace_id', 'sort_order', 'id'], unique=False)
    op.create_table('activities',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('compound_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('assay_name', sa.String(length=512), nullable=False),
    sa.Column('metric', sa.String(length=128), nullable=False),
    sa.Column('operator', sa.Enum('=', '<', '<=', '>', '>=', '~', name='activity_operator', native_enum=False), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.String(length=128), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(assay_name) <> ''", name='ck_activities_assay_name_required'),
    sa.CheckConstraint("btrim(metric) <> ''", name='ck_activities_metric_required'),
    sa.CheckConstraint("operator IN ('=', '<', '<=', '>', '>=', '~')", name='ck_activities_operator'),
    sa.CheckConstraint('sort_order >= 0', name='ck_activities_nonnegative_order'),
        sa.ForeignKeyConstraint(['compound_id', 'paper_id', 'workspace_id'], ['compounds.id', 'compounds.paper_id', 'compounds.workspace_id'], name='fk_activities_compound_aggregate', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_id', 'paper_id', 'workspace_id'], ['evidence.id', 'evidence.paper_id', 'evidence.workspace_id'], name='fk_activities_evidence_aggregate', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activities_compound_order', 'activities', ['compound_id', 'sort_order', 'id'], unique=False)
    op.create_table('lineage_members',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('lineage_id', sa.UUID(), nullable=False),
    sa.Column('compound_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('root', 'intermediate', 'terminal', 'unspecified', name='lineage_member_role', native_enum=False, length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('root', 'intermediate', 'terminal', 'unspecified')", name='ck_lineage_members_role'),
    sa.CheckConstraint('sort_order >= 0', name='ck_lineage_members_nonnegative_order'),
    sa.ForeignKeyConstraint(['compound_id', 'paper_id', 'workspace_id'], ['compounds.id', 'compounds.paper_id', 'compounds.workspace_id'], name='fk_lineage_members_compound_aggregate', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lineage_id', 'paper_id', 'workspace_id'], ['lineages.id', 'lineages.paper_id', 'lineages.workspace_id'], name='fk_lineage_members_lineage_aggregate', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lineage_id', 'compound_id', 'paper_id', 'workspace_id', name='uq_lineage_members_edge_endpoint'),
    sa.UniqueConstraint('lineage_id', 'compound_id', name='uq_lineage_members_lineage_compound')
    )
    op.create_index('ix_lineage_members_lineage_order', 'lineage_members', ['lineage_id', 'sort_order'], unique=False)
    op.create_table('structure_source_images',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('compound_id', sa.UUID(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('x0', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('y0', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('x1', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('y1', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('source_context', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('crop_status', sa.Enum('pending', 'ready', 'failed', name='structure_image_crop_status', native_enum=False, length=16), nullable=False),
    sa.Column('crop_asset_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("crop_status IN ('pending', 'ready', 'failed')", name='ck_structure_source_images_crop_status'),
    sa.CheckConstraint("source_sha256 ~ '^[0-9a-f]{64}$'", name='ck_structure_source_images_source_sha256'),
    sa.CheckConstraint('page_number > 0', name='ck_structure_source_images_positive_page'),
    sa.CheckConstraint('x0 >= 0 AND x0 < x1 AND x1 <= 1 AND y0 >= 0 AND y0 < y1 AND y1 <= 1', name='ck_structure_source_images_normalized_bbox'),
    sa.ForeignKeyConstraint(['compound_id', 'paper_id', 'workspace_id'], ['compounds.id', 'compounds.paper_id', 'compounds.workspace_id'], name='fk_structure_source_images_compound_aggregate', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crop_asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_structure_source_images_compound_page', 'structure_source_images', ['compound_id', 'page_number'], unique=False)
    op.create_table('structures',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('compound_id', sa.UUID(), nullable=False),
    sa.Column('smiles', sa.Text(), nullable=True),
    sa.Column('canonical_smiles', sa.Text(), nullable=True),
    sa.Column('molfile', sa.Text(), nullable=True),
    sa.Column('inchi', sa.Text(), nullable=True),
    sa.Column('inchikey', sa.String(length=64), nullable=True),
    sa.Column('depiction_asset_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'reviewer_confirmed', 'unresolved', 'not_reported', name='structure_status', native_enum=False, length=24), nullable=False),
    sa.Column('input_method', sa.Enum('ai_prefill', 'manual_smiles', 'structure_editor', name='structure_input_method', native_enum=False, length=24), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("input_method IN ('ai_prefill', 'manual_smiles', 'structure_editor')", name='ck_structures_input_method'),
    sa.CheckConstraint("status IN ('draft', 'reviewer_confirmed', 'unresolved', 'not_reported')", name='ck_structures_status'),
    sa.ForeignKeyConstraint(['compound_id', 'paper_id', 'workspace_id'], ['compounds.id', 'compounds.paper_id', 'compounds.workspace_id'], name='fk_structures_compound_aggregate', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depiction_asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('compound_id', name='uq_structures_compound')
    )
    op.create_table('lineage_edges',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('lineage_id', sa.UUID(), nullable=False),
    sa.Column('parent_compound_id', sa.UUID(), nullable=False),
    sa.Column('child_compound_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=128), nullable=False),
    sa.Column('modification_summary', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Enum('draft', 'reviewer_confirmed', 'unresolved', name='lineage_edge_review_status', native_enum=False, length=24), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(relation_type) <> ''", name='ck_lineage_edges_relation_required'),
    sa.CheckConstraint("review_status IN ('draft', 'reviewer_confirmed', 'unresolved')", name='ck_lineage_edges_review_status'),
    sa.CheckConstraint('parent_compound_id <> child_compound_id', name='ck_lineage_edges_no_self_loop'),
    sa.CheckConstraint('sort_order >= 0', name='ck_lineage_edges_nonnegative_order'),
    sa.ForeignKeyConstraint(['lineage_id', 'child_compound_id', 'paper_id', 'workspace_id'], ['lineage_members.lineage_id', 'lineage_members.compound_id', 'lineage_members.paper_id', 'lineage_members.workspace_id'], name='fk_lineage_edges_child_membership', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lineage_id', 'paper_id', 'workspace_id'], ['lineages.id', 'lineages.paper_id', 'lineages.workspace_id'], name='fk_lineage_edges_lineage_aggregate', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lineage_id', 'parent_compound_id', 'paper_id', 'workspace_id'], ['lineage_members.lineage_id', 'lineage_members.compound_id', 'lineage_members.paper_id', 'lineage_members.workspace_id'], name='fk_lineage_edges_parent_membership', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'paper_id', 'workspace_id', name='uq_lineage_edges_id_paper_workspace'),
    sa.UniqueConstraint('lineage_id', 'parent_compound_id', 'child_compound_id', name='uq_lineage_edges_directed_pair')
    )
    op.create_index('ix_lineage_edges_endpoints', 'lineage_edges', ['lineage_id', 'parent_compound_id', 'child_compound_id'], unique=False)
    op.create_table('edge_evidence_links',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('edge_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('supports', 'contradicts', 'contextual', name='edge_evidence_role', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('supports', 'contradicts', 'contextual')", name='ck_edge_evidence_links_role'),
    sa.ForeignKeyConstraint(['edge_id', 'paper_id', 'workspace_id'], ['lineage_edges.id', 'lineage_edges.paper_id', 'lineage_edges.workspace_id'], name='fk_edge_evidence_links_edge_aggregate', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id', 'paper_id', 'workspace_id'], ['evidence.id', 'evidence.paper_id', 'evidence.workspace_id'], name='fk_edge_evidence_links_evidence_aggregate', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edge_id', 'evidence_id', name='uq_edge_evidence_links_edge_evidence')
    )
    op.create_index('ix_edge_evidence_links_evidence', 'edge_evidence_links', ['evidence_id', 'edge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_edge_evidence_links_evidence', table_name='edge_evidence_links')
    op.drop_table('edge_evidence_links')
    op.drop_index('ix_lineage_edges_endpoints', table_name='lineage_edges')
    op.drop_table('lineage_edges')
    op.drop_table('structures')
    op.drop_index('ix_structure_source_images_compound_page', table_name='structure_source_images')
    op.drop_table('structure_source_images')
    op.drop_index('ix_lineage_members_lineage_order', table_name='lineage_members')
    op.drop_table('lineage_members')
    op.drop_index('ix_activities_compound_order', table_name='activities')
    op.drop_table('activities')
    op.drop_index('ix_lineages_workspace_order', table_name='lineages')
    op.drop_table('lineages')
    op.drop_index('ix_evidence_workspace_page', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_compounds_workspace_order', table_name='compounds')
    op.drop_table('compounds')
    # ### end Alembic commands ###
