<script setup lang="ts">
import { onMounted, ref } from "vue";
import { fetchAdminImports, dryRunImport, applyImport } from "./api";
const imports = ref<Record<string,unknown>[]>([]); const sourceRoot = ref("baseline"); const report = ref<Record<string,unknown>|null>(null); const busy = ref(false); const error = ref<string|null>(null);
async function load(){try{imports.value=await fetchAdminImports()}catch{error.value="导入批次未能读取。"}}
async function preview(){busy.value=true;error.value=null;try{report.value=await dryRunImport(sourceRoot.value)}catch{error.value="预检失败，请检查来源配置。"}finally{busy.value=false}}
async function apply(){busy.value=true;try{report.value=await applyImport(sourceRoot.value);await load()}catch{error.value="导入未能应用。"}finally{busy.value=false}}
onMounted(load);
</script>
<template><div class="admin-page"><header class="page-heading"><div><p class="eyebrow">STAGED INGESTION</p><h1>导入管理</h1><p>先在 staging 中校验快照，再由系统生成可审批的变更。</p></div></header><section class="admin-panel import-controls"><label for="source-root">来源配置</label><input id="source-root" v-model="sourceRoot" autocomplete="off"><button class="button-secondary" type="button" :disabled="busy" @click="preview">预检</button><button class="button-primary" type="button" :disabled="busy" @click="apply">应用到 staging</button><p v-if="error" role="alert">{{ error }}</p></section><section v-if="report" class="admin-panel"><h2>预检结果</h2><pre>{{ JSON.stringify(report,null,2) }}</pre></section><section class="admin-panel"><h2>导入批次</h2><table><thead><tr><th>状态</th><th>指纹</th><th>开始时间</th></tr></thead><tbody><tr v-for="item in imports" :key="String(item.id)"><td>{{ item.status }}</td><td><code>{{ item.source_fingerprint }}</code></td><td>{{ item.started_at }}</td></tr><tr v-if="imports.length===0"><td colspan="3" class="empty">暂无导入批次</td></tr></tbody></table></section></div></template>
<style scoped>.admin-page{padding:clamp(24px,4vw,52px)}.admin-panel{margin-bottom:18px;padding:20px;border:1px solid var(--line);background:#fff;overflow:auto}.import-controls{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.import-controls label{font-size:.75rem;font-weight:700}.import-controls input{min-height:38px;padding:7px 10px;border:1px solid var(--line);border-radius:6px}.import-controls p{flex-basis:100%;color:var(--danger)}h2{margin:0 0 14px;font:600 1.2rem Georgia,serif}pre{max-height:280px;overflow:auto;background:var(--canvas);padding:14px;font-size:.72rem}table{width:100%;border-collapse:collapse;font-size:.78rem}th,td{padding:12px;border-bottom:1px solid var(--line);text-align:left}.empty{text-align:center;color:var(--ink-500)}</style>
