<script setup lang="ts">
import { onMounted, ref } from "vue";
import { ApiError } from "../api/client";
import { createAdminUser, fetchAdminUsers, resetUserToDefault, revokeUserSessions, updateUserEnabled, type AdminUser } from "./api";
import AdminTableState from "./AdminTableState.vue";

const users = ref<AdminUser[]>([]); const loading = ref(true); const error = ref<string | null>(null); const saving = ref<string | null>(null); const showCreate = ref(false); const newUsername = ref(""); const newDisplayName = ref(""); const newRole = ref<AdminUser["role"]>("reviewer");
async function load() { loading.value = true; error.value = null; try { users.value = await fetchAdminUsers(); } catch (e) { error.value = e instanceof ApiError ? `${e.message} (${e.requestId ?? "无请求编号"})` : "请稍后重试。"; } finally { loading.value = false; } }
async function toggle(user: AdminUser) { saving.value = user.username; try { const updated = await updateUserEnabled(user.id, !user.is_enabled); Object.assign(user, updated); } catch { error.value = "用户状态未能更新。"; } finally { saving.value = null; } }
async function revoke(user: AdminUser) { saving.value = user.username; try { await revokeUserSessions(user.id); } catch { error.value = "会话未能撤销。"; } finally { saving.value = null; } }
async function resetDefault(user: AdminUser) { if (!window.confirm(`确认将 ${user.username} 重置为统一默认密码？该用户的现有会话将被撤销。`)) return; saving.value = user.username; try { const updated = await resetUserToDefault(user.id); Object.assign(user, updated); } catch { error.value = "密码未能重置。"; } finally { saving.value = null; } }
async function createUser() { if (!newUsername.value.trim() || !newDisplayName.value.trim()) return; try { const created = await createAdminUser({ username: newUsername.value, display_name: newDisplayName.value, role: newRole.value }); users.value.push(created); showCreate.value = false; newUsername.value = ""; newDisplayName.value = ""; newRole.value = "reviewer"; } catch { error.value = "账号未能创建。"; } }
onMounted(load);
</script>
<template><div class="admin-page" data-admin-users><header class="page-heading"><div><p class="eyebrow">ADMINISTRATION</p><h1>用户管理</h1><p>管理访问角色、启用状态与活动会话。</p></div><button class="button-primary" type="button" @click="showCreate = !showCreate">{{ showCreate ? "取消" : "创建账号" }}</button></header><form v-if="showCreate" class="admin-panel create-form" @submit.prevent="createUser"><label>用户名<input v-model="newUsername" required autocomplete="off"></label><label>显示名称<input v-model="newDisplayName" required></label><label>角色<select v-model="newRole" name="role"><option value="visitor">访客</option><option value="reviewer">核查员</option><option value="admin">管理员</option></select></label><button class="button-primary" type="submit">保存账号</button></form><AdminTableState :loading="loading" :error="error"><section class="admin-panel"><table><thead><tr><th>用户名</th><th>显示名称</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="user in users" :key="user.username"><td>{{ user.username }}</td><td>{{ user.display_name }}</td><td>{{ user.role }}</td><td>{{ user.is_enabled === false ? "已停用" : "启用" }}</td><td class="actions"><button type="button" :disabled="saving === user.username" @click="toggle(user)">{{ user.is_enabled === false ? "启用" : "停用" }}</button><button data-reset-default type="button" :disabled="saving === user.username" @click="resetDefault(user)">重置为默认密码</button><button type="button" :disabled="saving === user.username" @click="revoke(user)">撤销会话</button></td></tr><tr v-if="users.length === 0"><td colspan="5" class="empty">暂无账号</td></tr></tbody></table></section></AdminTableState></div></template>
<style scoped>.admin-page{padding:clamp(24px,4vw,52px)}.admin-panel{padding:20px;border:1px solid var(--line);background:#fff;overflow:auto}.create-form{display:flex;align-items:end;gap:14px;flex-wrap:wrap;margin-bottom:18px}.create-form label{display:grid;gap:6px;color:var(--ink-650);font-size:.7rem;font-weight:700}.create-form input,.create-form select{min-height:36px;padding:6px 9px;border:1px solid var(--line);border-radius:6px;background:#fff}table{width:100%;border-collapse:collapse;font-size:.78rem}th,td{padding:13px 12px;border-bottom:1px solid var(--line);text-align:left;white-space:nowrap}th{color:var(--ink-500);font-size:.68rem;letter-spacing:.08em}.actions{display:flex;gap:8px}.actions button{padding:6px 10px;border:1px solid var(--line);border-radius:6px;background:#fff;color:var(--ink-700);cursor:pointer}.actions button:hover{border-color:var(--forest-750)}.empty{text-align:center;color:var(--ink-500)}</style>
